-- CreateTable
CREATE TABLE "photos" (
    "id" VARCHAR(8) NOT NULL,
    "url" VARCHAR(255) NOT NULL,
    "width" INTEGER NOT NULL,
    "height" INTEGER NOT NULL,
    "extension" VARCHAR(255) NOT NULL,
    "aspectRatio" REAL DEFAULT 1.5,
    "blurData" TEXT,
    "title" VARCHAR(255),
    "caption" TEXT,
    "semanticDescription" TEXT,
    "tags" TEXT[],
    "make" VARCHAR(255),
    "model" VARCHAR(255),
    "focalLength" SMALLINT,
    "focalLengthIn35mmFormat" SMALLINT,
    "lensMake" VARCHAR(255),
    "lensModel" VARCHAR(255),
    "fNumber" REAL,
    "iso" SMALLINT,
    "exposureTime" DOUBLE PRECISION,
    "exposureCompensation" REAL,
    "locationName" VARCHAR(255),
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "filmSimulation" VARCHAR(255),
    "priorityOrder" REAL,
    "takenAt" TIMESTAMPTZ NOT NULL,
    "takenAtNaive" VARCHAR(255) NOT NULL,
    "hidden" BOOLEAN,
    "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "photos_pkey" PRIMARY KEY ("id")
);
